bidding/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/',include("store.urls")),
    path('',include("core.urls")),
    path('',include("users.urls")),
    path('cart/',include('cart.urls',namespace='cart')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# if settings.DEBUG:
#     from django.conf.urls.static import static
#     urlpatterns+=static(settings.MEDIA_URL,
#                         document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views
app_name='cart'

urlpatterns=[
    path('',views.cartSummary,name='cartSummary'),
    path('add/',views.cartAdd,name='cartAdd'),
    path('delete/',views.cartDelete,name='cartDelete'),
    path('deleteBid/<bid_id>', views.deleteBid, name="deleteBid"),
    path('checkout',views.checkout, name="checkout"),
    path('checkout/checkoutConfirmation',views.checkoutConfirmation, name="checkoutConfirmation"),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store' #Para hacer las conexiones correspondientes entre templates de diferentes apps
# More info
# https://docs.djangoproject.com/en/3.0/intro/tutorial03/#namespacing-url-names

urlpatterns = [
    #path("cart",views.cart,name="cart"),
    path("bid/<int:id_product>/", views.goToBidProduct, name="bidProductPage"),
    path("stock/<int:id_product>/", views.goToStockProduct, name="stockProductPage"),
    path("uploadProduct",views.selectProduct,name="uploadProduct"),
    path("uploadBidProduct",views.BidProductCreateView.as_view(),name="uploadBidProduct"),
    path("uploadStockProduct",views.StockProductCreateView.as_view(),name="uploadStockProduct"),
]

cart/models.py
from django.db import models
from users.models import User
from store.models import Product,StockProduct,BidProduct

# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='order_user')
    fullName = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    phone = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    totalPaid = models.FloatField(max_length=50)
    orderKey = models.CharField(max_length=200)
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
    product = models.ForeignKey(StockProduct,related_name='order_items',on_delete=models.CASCADE)
    price = models.FloatField(max_length=50,default=1.0)
    quiantity = models.PositiveIntegerField(default=1)
    shipped = models.BooleanField(default = False)
    
class OrderBid(models.Model):
    order = models.ForeignKey(Order,related_name='bid',on_delete=models.CASCADE)
    product = models.ForeignKey(BidProduct,related_name='bidProduct',on_delete=models.CASCADE)
    price = models.FloatField(max_length=50,default=1.0)

store/models.py
from django.db import models
from users.models import Bid,User

# Create your models here.

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(isActive=True)

class Product(models.Model):
    productName = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    category = models.CharField(max_length=50)
    isActive = models.BooleanField(default=True)
    image = models.ImageField()
    objects = models.Manager()
    products = ProductManager()
    seller = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    class Meta:
        abstract = True

    def __str__(self):
        return self.productName
    
    def getDescription(self):
        return self.description

    def getCategory(self):
        return self.category
    
    def getImage(self):
        return self.image


CONDITION_CHOICES = (
    ('MALA','MALA'),
    ('BUENA', 'BUENA'),
    ('COMO NUEVO','COMO NUEVO'),
    ('NUEVO','NUEVO'),
)

class BidProduct(Product):
    currentBid = models.FloatField(blank=True,default=0)
    minBid = models.FloatField(default=0)
    condition = models.CharField(max_length=20, choices=CONDITION_CHOICES, default='BUENA')
    bidWinner = models.ForeignKey(User,related_name="BidWinner", null=True, on_delete=models.SET_NULL,blank=True)
    #bidWinner = models.OneToOneField(User, related_name="BidWinner", null=True, on_delete=models.SET_NULL, )
    sold = models.BooleanField(default=False)
    #createdBy = models.ForeignKey(User,on_delete=models.CASCADE,related_name="bidCreator",null=True)

    def save(self, *args, **kwargs):
        if not self.currentBid:
            self.currentBid = self.minBid
        super(BidProduct, self).save(*args, **kwargs)
    
    def getCurrentBid(self):
        return self.currentBid

    def getMinBid(self):
        return self.minBid

    def getCondition(self):
        return self.condition

    def getBidWinner(self):
        return self.bidWinner

class StockProduct(Product):
    price = models.FloatField(max_length=50)
    inventory = models.PositiveIntegerField(blank=True,default=1)
    sold = models.PositiveBigIntegerField(default=0)
    #createdBy = models.ForeignKey(User,on_delete=models.CASCADE,related_name="productCreator",null=True)

    def getPrice(self):
        return self.price

    def getInventory(self):
        return self.inventory

cart/forms.py
from django import forms
from cart.models import Order,OrderItem

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['fullName','address','city','phone']
        
class OrderItemForm(forms.ModelForm):
    class Meta:
        model: OrderItem
        fields = [None]

store/forms.py
from django import forms
from store.models import BidProduct, StockProduct

class BidForm(forms.ModelForm):
    currentBid = forms.IntegerField(label="Tu Puja")
    class Meta:
        model = BidProduct
        fields = ['currentBid']
        
class BidProductForm(forms.ModelForm):
    class Meta:
        model = BidProduct
        #fields = '__all__'
        exclude = ['seller', 'bidWinner', 'currentBid','sold']
    
class StockProductForm(forms.ModelForm):
    class Meta:
        model = StockProduct
        exclude = ['seller','sold']

cart/views.py
from django.http import response
from django.shortcuts import get_object_or_404, redirect, render
from .cart import Cart
from cart.models import Order,OrderItem
from store.models import BidProduct, StockProduct
from django.http import JsonResponse
from users.models import Bid, SystemNotification, User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.contrib import messages
from cart.forms import OrderForm,OrderItemForm
import string
import random

# Create your views here.

#Vista del carrito
def cartSummary(request):
    cart = Cart(request)
    if not request.user.is_authenticated:
        return render(request,'store/cart.html',{'cart':cart})
    bids = Bid.objects.filter(user=request.user)
    bid=[]
    for b in bids:
        if not b.product.sold:
            bid.append(b)
    return render(request,'store/cart.html',{'cart':cart,
                                             'biddedProducts':bid})
    

#Agrega al carrito el producto de stock
def cartAdd(request):
    cart = Cart(request)
    print("Hola")
    if request.POST.get('action')=='post':
        product_id = int(request.POST.get('productid'))
        product = get_object_or_404(StockProduct,id=product_id)
        if not request.user.is_authenticated: 
            return render(request, "store/stockProductTemplate.html", {'product' : product})
        elif product.inventory > 0:
            cart.add(product=product)
            response = JsonResponse({'test':'data'})
            #messages.success(request,"No puedes ingresar valores negativos")
        else:
            messages.warning(request,"No hay stock!");
            return render(request, "store/stockProductTemplate.html", {'product' : product})
        return response
    
def cartDelete(request):
    cart = Cart(request)
    if request.POST.get('action')=='post':
        product_id = int(request.POST.get('productid'))
        cart.delete(product=product_id)
        cartTotal = cart.get_total_price()
        response = JsonResponse({'subtotal':cartTotal})
        return response
    
def deleteBid(request, bid_id):
    bid = Bid.objects.get(pk = bid_id)
    bidProduct = bid.product
       
    bid.delete()
    if not Bid.objects.filter(product = bidProduct):
        print("No hay bidders. CurBid = minBid")
        bidProduct.currentBid = bidProduct.minBid
    else:
        prevBid = Bid.objects.all().last()
        bidProduct.currentBid = prevBid.userBid
        print("CurBid actualizada a la última puja")
    bidProduct.save()
    return redirect('cart:cartSummary')

def checkout(request):
    cart = Cart(request)
    if request.user.is_authenticated:
        if cart.__len__()==0:
            return redirect('cart:cartSummary')
        elif request.user.money>=cart.get_total_price():
            products_id=list(cart.cart.keys())
            for id in products_id:#Para comprobar si hay suficiente stock
                if cart.get_qty(str(id))>StockProduct.objects.get(id=id).inventory:
                    print("No hay suficiente stock")
                    return redirect("cart:cartSummary")
            if request.method == "POST":
                form = OrderForm(request.POST)
                if form.is_valid():#Verificar la longitud del número de teléfono ingresado ( 0< número/1,000,000,000 <10)
                    phone = float(form.cleaned_data['phone'])
                    if (phone/(1000000000)>=1) and (phone/(1000000000)<10):
                        order = form.save(commit=False)
                        order.orderKey = ''.join(random.choice(string.ascii_letters + string.digits )for i in range (15) )
                        order.totalPaid = cart.get_total_price()
                        order.user = request.user
                        order.save()
                        print(order)
                        request.method="GET"
                        return checkoutConfirmation(request)
                    else:
                        pass#Mandar alerta que el usuario ingresó un número incorrecto
            form = OrderForm()
            return render(request,"store/checkout.html",{'form':form})
        else:
            #print("Sin dinero suficiente!")
         # messages.warning(request,"No hay dinero suficiente");
            return redirect('users:addMoney')
    #print("No permitido, debes iniciar sesión")
    #messages.warning(request,"No permitido, debes iniciar sesión") #checar
    return HttpResponseNotAllowed("Not allowed")

def checkoutConfirmation(request):
    cart = Cart(request)
    if request.user.is_authenticated and cart.get_total_price()!=0:
        order = Order.objects.filter(user=request.user).last()#Puede generar errores
        if request.method == "POST":
            if "buy" in request.POST:
                products_id=list(cart.cart.keys())
                for id in products_id:
                    products = StockProduct.objects.get(id=id)
                    seller = products.seller
                    orderItem = OrderItem(order=order,product=products)
                    orderItem.price = cart.get_price(str(id))
                    orderItem.quiantity=cart.get_qty(str(id))
                    orderItem.save()
                    products.inventory -=cart.get_qty(str(id))  #Reduce el inventario
                    products.sold +=cart.get_qty(str(id))
                    products.save()
                    request.user.money -=cart.get_price(str(id))
                    request.user.save()
                    seller.money += cart.get_price(str(id))
                    newMessage = f'Ha realizado una venta! Ha vendido x{cart.get_qty(str(id))} del producto {products.productName}. Ve más detalles en el apartado de "Mis productos"'
                    SystemNotification.objects.create(toUser = seller, message = newMessage)
                    seller.save()
                newMessage = f'Su orden con clave: {order.orderKey} ha sido procesado! Puede checar en Mis Compras localizado en el header!'
                SystemNotification.objects.create(toUser = request.user, message = newMessage)
                cart.deleteAll()
                return redirect("users:myShoppings")    
            else:
                cart.deleteAll()
                order.delete()
                return redirect('core:index')
        return render(request,"store/checkoutConfirmation.html",{"cart":cart,"order":order})
    return HttpResponseNotAllowed("Not allowed")

store/views.py
from django.shortcuts import render,redirect
#from django.http import HttpResponse
from django.http import HttpResponseNotAllowed
from .models import BidProduct, Product,StockProduct
from store.forms import BidForm, BidProductForm,StockProductForm
from users.models import Bid, User
from django.views.generic.edit import CreateView

from django.contrib import messages
# Create your views here.

def cart(request):
    return render(request, "store/cart.html")

def goToBidProduct(request,id_product):
    product = BidProduct.objects.get(id=id_product)
    theForm = BidForm(instance=product)
    productCurrentBid = product.currentBid
    if product.isActive and product.bidWinner==None:#Condición para saber si sigue activo (Cuando termine la puja o el usuario así lo decida)
        print(product.bidWinner)#Debe mostrar None en terminal
        if request.method == "POST":
            theForm = BidForm(request.POST, instance=product)
            if not request.user.is_authenticated:
                return redirect('users:loginV')
            if theForm.is_valid():
                userMoney = request.user.money
                if(theForm.cleaned_data['currentBid'] < 0):
                    messages.warning(request,"No puedes hacer una puja con dinero negativo")
                else:
                    user_bid = theForm.cleaned_data['currentBid']
                    print("userBid: "+str(user_bid))
                    print("userMoney: "+str(userMoney))
                    print("product current bid: "+str(productCurrentBid))
                    if user_bid < userMoney and user_bid > productCurrentBid:
                        try:
                            #Puede generarse un error donde no exista el Bid
                            bid = Bid.objects.get(user=request.user,product=product)
                            print("Sobreescribiendo puja")
                            bid.userBid = user_bid
                            bid.save()
                        except:
                            print("Creando puja")
                            newBid = Bid.objects.create(user = request.user, userBid = user_bid, product=product)
                        theForm.save()
                        #print("BID SUCCESSFUL!") #use JavaScript alert() or some other UI notification
                        messages.success(request,"Puja exitosa")
                
                    else:
                        #print("YOU DONT HAVE ENOUGH MONEY OR YOUR BID IS TOO LOW")
                        messages.warning(request,"No tienes suficientes fondos o tu puja es muy baja")
        product = BidProduct.objects.get(id=id_product)
        theForm = BidForm(instance=product)
        return render(request, "store/bidProductTemplate.html", {"product" : product, "form":theForm})
    return HttpResponseNotAllowed("Not allowed")

def goToStockProduct(request,id_product):
    product = StockProduct.objects.get(id=id_product)
    if product.isActive:
        return render(request, "store/stockProductTemplate.html", {"product" : product})
    else:
        print("No puedes entrar! El usuario decidió que ya no está activo el producto")
        return HttpResponseNotAllowed("Not allowed")

def selectProduct(request):
    return render(request,"store/uploadProduct.html")

class BidProductCreateView(CreateView):
    model = BidProduct
    form_class = BidProductForm
    template_name = 'store/uploadBidProduct.html'
    #success_url = 'uploadProduct'
    
    #def get_success_url(self):
     #   return reverse_lazy('product_list')
    
    def form_valid(self, form):
        bidProduct = form.save(commit=False)
        bidProduct.seller = User.objects.get(id=self.request.user.id) 
        if( form.cleaned_data['minBid'] < 0):
            #print("No puedes ingresar valores negativos")
            messages.warning(self.request,"No puedes ingresar valores negativos")
            return redirect("store:uploadBidProduct")
        else:
            bidProduct.save()
            return redirect("core:index")

class StockProductCreateView(CreateView):
    model = StockProduct
    form_class = StockProductForm
    template_name = 'store/uploadStockProduct.html'
    
    def form_valid(self,form):
        stockProduct = form.save(commit=False)
        stockProduct.seller = User.objects.get(id=self.request.user.id)
        if( form.cleaned_data['price'] < 0):
            #print("No puedes ingresar valores negativos")
            messages.warning(self.request,"No puedes ingresar valores negativos")
            return redirect('store:uploadStockProduct')
        else:
            stockProduct.save()
            return redirect('core:index')

store/templates/store/bidProductTemplate.html
{% extends 'core/layout.html' %} 
{% load static %}   

{% block cssPath %} 
<link rel="stylesheet" href="{% static 'store/productTemplate.css' %}"  type="text/css"/>
{% endblock cssPath %}

{% if productFound %}

    {% block title %} {{product.productName}} {% endblock title%}

    <!--ALERT NOTIFICATION-->
    {% block alertMsg %}
        {% include 'core/messages.html' %}
    {% endblock alertMsg %}
    
    {% block body %} 
    <!--<div class="container">-->
    <div class="infoContainer">
    <div class="row">
    <div class="col-md-3 register-left my-auto">
        <div class="pictures">
            <img src="{{product.image.url}}"  alt="Product Image" width="500" height="auto" />
        </div>
    </div>
        
    <div class="col-md-9 register-right">
    <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <div id="littlePadding" class="col">
        <font style="color:black" align="center">

        <div class="productDescription">
            
            <div class="productName">
                <h1>{{ product.productName }}</h1>
            </div>

            <div class="price">
                <p>Puja más alta: ${{ product.currentBid}}</p>
            </div>

            <div class="description">
                <h3>Descripción:</h3>
                <p>{{ product.description }}</p>
            </div>

            <div class="category">
                <h3>Categoría: {{ product.category }} <h3>
            </div>

            <div class="condition">
                <h3>Condición:</h3>
                <h3 id="yeetCondition"> {{product.condition}}</h3>
                <!--<h3 for="id_condition"> a {{ product.condition }}</h3>-->
            </div>
            <p for="id_prueba">Tu puja debe ser mayor a la puja más alta!</p> 
            
            <div class="form">
                <form method="POST" >
                    {% csrf_token %}
                    {{form.as_p}}
                    <button id="buttonLogin" type="submit" name="BidProduct">PUJAR!</button>
                     <!--"submitBtn"-->
                </form>
            </div>
        </font>
        </div> 
    </div>
    </div>
    </div>
    </div>
    </div>  
    </div>
    <script src="{% static 'store/bidLabel.js'%}"></script>
    {% endblock body %}
{% else %}
    <h1>Product no encontrado!</h1>
{% endif %}
 

store/templates/store/cart.html
{% extends 'core/layout.html' %}

{% block title %}
    Carrito
{% endblock title %}

{% if user.is_authenticated %}
  {% block body %}
    <!--Mostrar el carrito de compras xd-->
        <main class="pt-5">
          <div class="container" style="max-width: 1000px">
            <div class="col-12">
              <h1 class="h2">Tu Carrito</h1>
            </div>
            <div class="col-12">
              <p>Administra tus <b>artículos</b> de tu carrito</p>
            </div>
            <hr />
          </div>
          <div class="container" style="max-width: 1000px">
            <div class="row g-3">
              <div class="col-12 bg-light p-3 d-flex justify-content-between">
                <div class="d-flex d-flex-inline">
                  <div class="pe-3">Tu orden</div>
                </div>
                <div class="text-end">
                  <div class="">Sub Total: <span class="fw-bold">$</span><div id="subtotal" class="d-inline-flex fw-bold">{{cart.get_subtotal_price}}</div></div>
                  <div id="">Envío <span class="small">(Entrega al día siguiente)</span>: <span class="fw-bold">Gratis!</span></div>
                  <div class="pt-2">Total a pagar: <span class="fw-bold h5">$</span><span id="total" class="fw-bold h5">{{cart.get_total_price}}</span></div>
                  
                </div>
              </div>
              <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
                <div class="d-grid gap-2 ">
                  <a role="button" href="{% url 'cart:checkout' %}" class="btn btn-success fw-bold" type="button">Checkout</a>
                </div>
              </div>
              <div class="col-md-7 col-lg-8 p-0">
                {% for item in cart %}
              {% with product=item.product %}<!--Importante para mostrar la información de los productos-->
              <div data-index="{{product.id}}" class="row mb-4 border product-item">
                <div class="col-md-3 col-lg-2 order-md-first bg-light">
                  <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ product.image.url }}">
                </div>
                <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                  <a href="http://127.0.0.1:8000/products/stock/{{product.id}}" class="text-decoration-none text-reset">
                    <h1 class="h5 pt-2">{{ product.productName }}</h1>
                  </a>
                  <div class="border">
                    <div class="col border-bottom">
                      <div class="row p-3">
                        <div class="col-6">Unidades: {{item.qty}}</div>
                        <div class="col-6 text-end"><span class="h6 fw-bold">${{ product.price }}</span></div>
                      </div>
                    </div>
                    <div class="col">
                      <div class="row p-3">
                        <div class="col-12">
                          <button type="button" id="delete-button" data-index="{{product.id}}"
                            class="btn btn-outline-secondary btn-sm delete-button">
                            Eliminar
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endwith %}
              {% endfor %}
              {% for item in biddedProducts  %}
              <div data-index="{{item.id}}" class="row mb-4 border product-item">
                <div class="col-md-3 col-lg-2 order-md-first bg-light">
                  <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ item.product.image.url }}">
                </div>
                <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                  <a href="http://127.0.0.1:8000/products/bid/{{item.product.id}}" class="text-decoration-none text-reset">
                    <h1 class="h5 pt-2">{{ item.product.productName }}</h1>
                  </a>
                  <div class="border">
                    <div class="col border-bottom">
                      <div class="row p-3">
                        <div class="col-6">Artículo de apuesta</div>
                        <div class="col-6 text-end"><span class="h6 fw-bold">
                          {% if item.userBid >= item.product.currentBid %}

                          Eres la puja más alta! con: ${{ item.userBid }}
                          {%else%}
                          No eres la puja más alta, con ${{ item.userBid }}
                          {%endif%}
                        </span></div>
                      </div>
                    </div>
                    <div class="col">
                      <div class="row p-3">
                        <div class="col-12">
                          <a href = "{% url 'cart:deleteBid' item.id %}" class="btn btn-outline-danger btn-sm">Borrar Puja</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
              </div>
            </div>            
          </div>
        </main>

          <script>
            $(document).on('click','.delete-button',function(e){
                e.preventDefault();
                var prodid = $(this).data('index')
                $.ajax({
                    type:'POST',
                    url:'{% url "cart:cartDelete" %}',
                    data:{
                        productid:$(this).data('index'),
                        csrfmiddlewaretoken:"{{csrf_token}}",
                        action:'post'
                    },
                    success: function(json){
                        $('.product-item[data-index="'+prodid+'"]').remove();
                        document.getElementById("subtotal").innerHTML = json.subtotal
                    },
                    error: function(xhr,errmsg,err){}
                });
            })
        </script>
        {% endblock body %}
{% else %}
  <h1>Necesitas tener iniciada sesión</h1>
{% endif %}

store/templates/store/checkout.html
{% extends 'core/layout.html' %}
{% load static %}   

{% block cssPath %} 
<link rel="stylesheet" href="{% static 'users/formStyle.css' %}"  type="text/css"/>
{% endblock cssPath %}

<link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

{% block title %}
    Checkout
{% endblock title %}

<!--ALERT NOTIFICATION-->
{% block alertMsg %}
    {% include 'core/messages.html' %}
{% endblock alertMsg %}

{% block body %}
<div class="container">
   <div class="registration-form">  
    <div class="form">
    <center>
    <form method="POST" action="{% url 'cart:checkout' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button id="buttonLogin" type="submit" name="Upload">Continuar</button>
    </form>
    </div>
   </div>
   <script src="{% static 'store/checkoutLabels.js'%}"></script>
</div>

{%endblock body%}

store/templates/store/checkoutConfirmation.html
{% extends 'core/layout.html' %}

{% load static %}

{% block title %}
    Carrito
{% endblock title %}

{% block cssPath %} 
    <link rel="stylesheet" href="{% static 'store/checkout.css' %}"  type="text/css"/>
{% endblock cssPath %}

{% block body %}

<div class="container">
    <div class="row m-0">
        <div class="col-lg-7 pb-5 pe-lg-5 cart">
            <div class="row">
                <div class="title">
                    <h1>Productos</h1>
                </div>
    
                <div class="row m-0 groupProducts">
                    {%for item in cart%}
                        {%with product=item.product%}
                        <div id="rowProduct" class="row border-top border-bottom">
                            <div class="row main align-items-center">
                                <div class="col">
                                    <div><img id="imagen-checkout" src="{{product.image.url}}" alt="imagenProducto"></div>
                                </div>
                                <div class="col">
                                    <div class="row">{{product.productName}}</div>
                                    <div class="row">Cantidad: {{item.qty}}</div>
                                    <div class="row">Precio por unidad: {{product.price}}</div>
                                </div>
                            </div>
                        </div>
                        {%endwith%}
                    {%endfor%}
                </div>
            </div>
        </div>
        
        <div class="col summary">
            <h1>Informacion de tu orden</h1>
            <div class="summaryContent">
                <div class="items">Nombre: {{order.fullName}}</div>
                <div class="items">Direccion: {{order.address}}</div>
                <div class="items">Ciudad: {{order.city}}</div>
                <div class="items">Telefono: {{order.phone}}</div>
            </div>
            <div class="priceBackground">
                <div class="row">
                    <div class="totalPriceTag col">
                        Precio total: 
                    </div>
                    <div class="totalPrice col">
                        {{cart.get_total_price}}
                    </div>
                </div>
            </div>
            <div class="checkoutButtons">
                <div class="form">
                    <form method="POST" action="{% url 'cart:checkoutConfirmation' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button id="submitBtn" type="submit" name="buy">Realizar compra</button>
                        <button id="submitBtn" type="submit" name="cancel">Cancelar</button>
                    </form>
                </div>
            </div>
        </div>
        
        
    </div>
</div>


{%endblock body%}

store/templates/store/index.html
{% extends 'store/layout.html' %}

{% block title %}
    INDEX
{% endblock title %}

{% block body %}
    <h1>INDEX <h1>
{% endblock body %}

store/templates/store/uploadBidProduct.html
{% extends 'core/layout.html' %}

{% load static %}

{% block cssPath %}
    <link rel="stylesheet" href="{% static 'store/bidUpload.css' %}"  type="text/css"/>
{% endblock cssPath %}

{% block title %}
    Subir Producto
{% endblock title %}

<!--ALERT NOTIFICATION-->
{% block alertMsg %}
    {% include 'core/messages.html' %}
{% endblock alertMsg %}

{% block body %}
    <!--Form para subir un producto-->
    <div class="container register">
        <div class="blankspace1">
        </div>
        <div class="form-title">
            Sube un producto
        </div>
        <div class="form-product">
            <div class="form">
                <form method="POST" action="{% url 'store:uploadBidProduct' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button id="submitBtn" type="submit" name="UploadProduct">Subir Producto</button>
                    <button id="submitBtn" type="submit" name="Cancel">Cancelar</button>
                </form>
            </div>
        </div>
        <div class="blankspace2">
        </div>
        <script src="{% static 'store/buttons1.js'%}"></script>
        <script src="{% static 'store/uploadBid.js'%}"></script>
    </div>
{% endblock body %}