bidding/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/',include("store.urls")),
    path('',include("core.urls")),
    path('',include("users.urls")),
    path('cart/',include('cart.urls',namespace='cart')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# if settings.DEBUG:
#     from django.conf.urls.static import static
#     urlpatterns+=static(settings.MEDIA_URL,
#                         document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views
app_name='cart'

urlpatterns=[
    path('',views.cartSummary,name='cartSummary'),
    path('add/',views.cartAdd,name='cartAdd'),
    path('delete/',views.cartDelete,name='cartDelete'),
    path('deleteBid/<bid_id>', views.deleteBid, name="deleteBid"),
    path('checkout',views.checkout, name="checkout"),
    path('checkout/checkoutConfirmation',views.checkoutConfirmation, name="checkoutConfirmation"),
]

core/urls.py
from django.urls.conf import path
from . import views

app_name = 'core'
urlpatterns = [
    path("",views.index,name="index"),
    path("FAQ",views.FAQ,name="FAQ"),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store' #Para hacer las conexiones correspondientes entre templates de diferentes apps
# More info
# https://docs.djangoproject.com/en/3.0/intro/tutorial03/#namespacing-url-names

urlpatterns = [
    #path("cart",views.cart,name="cart"),
    path("bid/<int:id_product>/", views.goToBidProduct, name="bidProductPage"),
    path("stock/<int:id_product>/", views.goToStockProduct, name="stockProductPage"),
    path("uploadProduct",views.selectProduct,name="uploadProduct"),
    path("uploadBidProduct",views.BidProductCreateView.as_view(),name="uploadBidProduct"),
    path("uploadStockProduct",views.StockProductCreateView.as_view(),name="uploadStockProduct"),
]

users/urls.py
from django.urls.conf import path
from . import views

app_name = 'users'
urlpatterns = [
    path("login",views.loginV,name = "loginV"),
    path("signup", views.signup, name = "signup"),
    path("profile", views.goToProfile, name="myProfile"),
    path("logoutUser", views.logoutUser, name = "logout"),
    path("updateProfile",views.updateProfile,name="updateProfile"),
    path("addMoney",views.updateMoney,name="addMoney"),
    path("myProduts",views.myProducts,name="myProducts"),
    path("notifications",views.notifications,name="notifications"),
    path('deleteUserNotification/<notification_id>', views.deleteUserNotification, name="deleteUserNotification"),
    path('deleteBidNotification/<notification_id>', views.deleteBidNotification, name="deleteBidNotification"),
    path('deleteSystemNotification/<notification_id>', views.deleteSystemNotification, name="deleteSystemNotification"),
    path("deleteUser",views.deleteUser,name="deleteUser"),
    path("myProducts/<int:id_product>/updateStockProduct",views.UpdateStockGeneral.as_view(),name="updateStock"),
    path("myProducts/<int:id_product>/updateBidProduct",views.UpdateBidGeneral.as_view(),name="updateBid"),
    path("myProducts/<int:id_bid>/bidOrder",views.bidOrder,name="bidOrder"),
    path("myProducts/orders",views.orders,name="orders"),
    path("myProducts/<int:id_order>/order",views.order,name="order"),
    path("myShoppings",views.myShoppings,name="myShoppings"),
    path("myShoppings/<int:id_order>/status",views.status,name="status"),
]

core/views.py
from django.shortcuts import render
from store.models import StockProduct,BidProduct

# Create your views here.
def index(request):
    return render(request,"core/index.html")

def FAQ(request):
    return render(request,"core/FAQ.html")

def index(request):
	context = {
        'stockProducts':reversed(StockProduct.objects.filter(isActive = True)),
        'bidProducts':reversed(BidProduct.objects.filter(isActive=True,bidWinner=None))
    }
	return render(request,'core/index.html',context)

core/templates/core/FAQ.html
{% extends 'core/layout.html' %}
{% load static %}

{% block cssPath %} 
  <link rel="stylesheet" href="{% static 'core/styleFAQ.css' %}"  type="text/css"/>
{% endblock cssPath %}

<link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

{% block title %}
    INDEX
{% endblock title %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
{% block body %}
      <div class="container">
        <div class="header-title">
          <div class="header-style">
            <h1>Preguntas Frecuentes:</h1>
          </div>
        </div>
        
        <!--<div class="FAQ-container">
          <div class="faq-list">
            <ul class="faq-questions">
              <li class="faq-expandable2">
                <button type="button" class="faq-button">¿Cómo agrego artículos a mi carrito?</button>
                <div class="faq-answer">
                  <p>Una vex hayas iniciado sesión, da clic en cualquier artículo que desees obtener y luego da clic en Agregar al carrito. ¡Asi de sencillo!
                     Es muy similar a como funcionan las subastas. Al optar por subir tu producto
                     por una puja, los demás usuarios tendrán hasta 24 hrs. para ofertar el mejor precio para tu 
                     producto. Al finalizar el día, el usuario con la mejor propuesta económica se habrá llevado tu producto!.
                  </p>
                </div>
              </li>
              <li class="faq-expandable2">
                <button type="button" class="faq-button">¿Cómo puedo vender mis productos?</button>
                <div class="faq-answer">
                  <p>Haz clic en el apartado "Mi perfil" y busca la opción "Subir un producto".
                     Puedes elegir entre subir un producto con precio fijo o iniciar una puja.
                  </p>
                </div>
              </li>
              <li class="faq-expandable2">
                <button type="button" class="faq-button">¿Qué es una puja?</button>
                <div class="faq-answer">
                  <p>Es muy similar a como funcionan las subastas. Al optar por subir tu producto
                     por una puja, los demás usuarios tendrán hasta 24 hrs. para ofertar el mejor precio para tu 
                     producto. Al finalizar el día, el usuario con la mejor propuesta económica se habrá llevado tu producto!
                  </p>
                </div>
              </li>
            </ul>
          </div>
        </div>*/ -->
        <!--Section: FAQ-->
<section>
  <div class="row">
    <div class="col-md-6 col-lg-4 mb-4">
      <h6 class="mb-3 text-primary"><i class="far fa-paper-plane text-primary pe-2"></i> ¿Puedo subir
        mas de un producto?</h6>
      <p>
        <strong><u>¡Absolutamente!</u></strong> Puedes subir cuantos productos desees, 
        incluso si son de tipos diferentes. Para ver o modificar el estado de tus
        productos, puedes ir a la seccion "Mis Productos" ¡o checar las notificaciones!
      </p>
    </div>

    <div class="col-md-6 col-lg-4 mb-4">
      <h6 class="mb-3 text-primary"><i class="fas fa-pen-alt text-primary pe-2"></i> ¿Qué es
        un producto de apuesta?</h6>
      <p>
        <strong><u>Es un producto en subasta.</u></strong> Si has subido
        un producto de apuesta, puedes terminar el plazo de pujas en cualquier momento
        presionando el botón "Terminar apuesta" al hacer clic en dicho producto
        desde el menú "Mis Productos". Si tu has hecho una puja a algún producto, 
        se te notificará cuando dicho plazo termine desde el menu "Notificaciones".
      </p>
    </div>

    <div class="col-md-6 col-lg-4 mb-4">
      <h6 class="mb-3 text-primary"><i class="fas fa-user text-primary pe-2"></i> ¿Qué hace
        el botón "Checkout" del carrito?
      </h6>
      <p>
        Procede a la compra de tus productos de stock (y los de apuesta,
        si el plazo ya ha vencido). Se te solicitará rellenar un formulario
        de confirmación de datos para que el o los vendedores puedan ubicarte
        y entregar tus productos.
      </p>
    </div>

    <div class="col-md-6 col-lg-4 mb-4">
      <h6 class="mb-3 text-primary"><i class="fas fa-rocket text-primary pe-2"></i> ¿Por qué
        no me aparecen todos los menús?
      </h6>
      <p>
        Para tener acceso completo a las caracteristicas de PulgApp, 
        debes tener una cuenta e iniciar sesión.
      </p>
    </div>

    <div class="col-md-6 col-lg-4 mb-4">
      <h6 class="mb-3 text-primary"><i class="fas fa-home text-primary pe-2"></i> ¿Puedo 
        agregar más dinero?
      </h6>
      <p><strong><u>Parcialmente, si</u>.</strong> Dado que PulgApp es una aplicación 
        diseñada por estudiantes primerizos, la moneda usada en PulgApp es ficticia y las transacciones no son reales.</p>
    </div>

    <div class="col-md-6 col-lg-4 mb-4">
      <h6 class="mb-3 text-primary"><i class="fas fa-book-open text-primary pe-2"></i> ¿Cómo
        elimino mi cuenta?</h6>
      <p>
        Lamentamos su decisión. Para irse de PulgApp de manera definitiva, presione el botón 
        "Eliminar cuenta" desde el menú "Mi perfil".
      </p>
    </div>
  </div>
</section>
<!--Section: FAQ-->
      </div>
</div>
{% endblock body %}

core/templates/core/index.html
{% extends 'core/layout.html' %}

{% block title %}
    INDEX
{% endblock title %}

{% block body %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="pb-3 h5">Todos los productos</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {%for product in stockProducts %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img class="img-fluid" alt="Responsive image" src="{{product.image.url}}">
                        <div class="card-body">
                            <p class="card-text">
                                <a class="text-dark text-decoration-none" href="http://127.0.0.1:8000/products/stock/{{product.id}}">{{product.productName}}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{product.inventory}} unidades disponibles!</small>
                                <small class="text-muted">${{product.price}} </small>
                            </div>
                        </div>
                    </div>
                </div>
                {%endfor %}
                {%for product in bidProducts %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img class="img-fluid" alt="Responsive image" src="{{product.image.url}}">
                        <div class="card-body">
                            <p class="card-text">
                                <a class="text-dark text-decoration-none" href="http://127.0.0.1:8000/products/bid/{{product.id}}">{{product.productName}}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">Puja más alta: ${{product.currentBid}}</small>
                            </div>
                        </div>
                    </div>
                </div>
                {%endfor %}
            </div>
        </div>
    </div>
{% endblock body %}

core/templates/core/layout.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'core/styleLayout.css' %}"  type="text/css"/>
    {% block cssPath %}{% endblock cssPath %}

  </head>
  <body>
    <div class="container-fluid">
        <header>
          <nav id="navHeader1" class="navbar navbar-expand-lg">
            <div class="container">
              <a class="navbar-brand" href="{% url 'core:index' %}">
                <img src="{% static 'store/logo.png' %}"  alt="logo" class="logo">
              </a>       

              <!-- Button for mobile devices -->
              <button id="buttonHeader" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMobileToggle" aria-controls="navbarMobileToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarMobileToggle">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'store:uploadProduct' %}"> Subir</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:myProducts' %}">Mis productos</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:myShoppings' %}">Mis compras</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'cart:cartSummary' %}" id="iconRef">
                      <span id="iconImg" class="material-icons-outlined">shopping_cart</span>
                    </a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:notifications' %}" id="iconRef"> 
                      <span id="iconImg" class="material-icons-outlined">notifications</span>
                    </a></li>
                  {% else %}
                    <li class="nav-item">
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'cart:cartSummary' %}" id="iconRef">
                      <span id = "iconImg" class="material-icons-outlined">shopping_cart</span>
                      </a>
                    </li>
                  {% endif %}
                </ul>

                <div class="btn-group float-end">
                  {% if user.is_authenticated %}
                    <a id="profileButton" href="#" class="dropdown-toggle text-decoration-none" data-bs-toggle="dropdown">
                      <i class="bi bi-person-circle"></i>
                      <span>Hola, {{user.firstName}}</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                      <li><a href="{% url 'users:myProfile' %}" class="dropdown-item">Mi perfil</a></li>
                      <li><a href="{% url 'users:logout' %}" class="dropdown-item">Cerrar sesion</a></li>
                      <li>
                        <hr class="dropdown-divider">
                      </li>
                    </ul>
                  {% else %}
                    <a id="profileButton" href="#" class="dropdown-toggle text-decoration-none" data-bs-toggle="dropdown">
                      <i class="bi bi-person-circle"></i>
                      <span>Hola, invitado</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                      <li><a href="{% url 'users:loginV' %}" class="dropdown-item">Iniciar sesion</a></li>
                      <li><a href="{% url 'users:signup' %}" class="dropdown-item">Registrarse</a></li>
                    </ul>                  
                  {% endif %}
                </div>
              </div>              
            </div>
          </nav>
        </header>
        {% comment %} <!--CONTAINER FOR ALERT NOTIFICATION-->
        <div class="alert alert-danger" role="alert" id="msg">
          {% block alertMsg %}{% endblock alertMsg %}
        </div> {% endcomment %}

        <div class="main">
        <!--CONTAINER FOR ALERT NOTIFICATION-->
        {% block alertMsg %} {% endblock alertMsg %}
        {% block body %} {% endblock body %}  
        </div>
          <footer class="page-footer font-small">
            <div class="container text-center text-md-left">

              <!-- Footer Left Column -->
              <div class="row">
                <div class="col-md-3 mx-auto">
                  <h3>¡Alguna sugerencia? ¡Cuentanos!</h3>
                  <p class="footer-links">
                      <i>Nuestro e-mail</i>
                      |
                      <i>¡Llamanos!</i>
                      |
                      <i>Escríbenos ;)</i>
                  </p>            
                </div>
              
                <hr class="clearfix w-100 d-md-none">

                <!-- Footer Middle Column -->
                <div class="col-md-6 mt-md-0 mt-3">
                  <h3>Sobre nosotros</h3>
                  <p>Somos un peque&ntildeo grupo de estudiantes de 5to semestre de la Facultad de Ciencias de la Computacion
                    de la BUAP, entusiastas de la codificacion al servicio del usuario. </br>
                  </p>
                  <div class="col-md-12 ">
                    <div class="mb-5 flex-center" id="footer-icons">
                        <a href="{% url 'core:index' %}" class="social">
                            <img src="{% static 'store/fb.png' %}"  alt="socialImg" class="socialImg">
                        </a>
                        <a href="{% url 'core:index' %}" class="social">
                            <img src="{% static 'store/insta.png' %}"  alt="socialImg" class="socialImg">
                        </a>
                        <a href="{% url 'core:index' %}" class="social">
                            <img src="{% static 'store/twit.png' %}"  alt="socialImg" class="socialImg">
                        </a>              
                    </div>
                  </div>
                </div>

                <hr class="clearfix w-100 d-md-none">

                <!-- Footer Right Column -->
                <div id="FAQ-Support" class="col-md-3 mx-auto">
                  <a id="FAQ-link" href="{% url 'core:FAQ' %}"><h3>Preguntas Frecuentes</h3></a>            
                </div>

                <hr class="clearfix w-100 d-md-none">
            </div>
            <!--</div>-->
            <!-- Copyright -->
          </footer>
          <div id="copyright-id" class="footer-copyright text-center py-3">
              © 2020 Copyright
              <br>
              Todos los derechos reservados
            </div>
        <!--</div>-->
    </div>
      <!--SCRIPT ALERT NOTIFICATION-->
    <script>
        setTimeout(function(){
            if($('#msg').length > 0){
                $('#msg').remove();
            }
        }, 2000);
    </script>

  </body>
</html>

core/templates/core/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{message.tags}} m-2" id="msg" role="alert">
            {{message}}
        </div> 
    {% endfor %}
{% endif %}