bidding/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/',include("store.urls")),
    path('',include("core.urls")),
    path('',include("users.urls")),
    path('cart/',include('cart.urls',namespace='cart')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# if settings.DEBUG:
#     from django.conf.urls.static import static
#     urlpatterns+=static(settings.MEDIA_URL,
#                         document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views
app_name='cart'

urlpatterns=[
    path('',views.cartSummary,name='cartSummary'),
    path('add/',views.cartAdd,name='cartAdd'),
    path('delete/',views.cartDelete,name='cartDelete'),
    path('deleteBid/<bid_id>', views.deleteBid, name="deleteBid"),
    path('checkout',views.checkout, name="checkout"),
    path('checkout/checkoutConfirmation',views.checkoutConfirmation, name="checkoutConfirmation"),
]

users/urls.py
from django.urls.conf import path
from . import views

app_name = 'users'
urlpatterns = [
    path("login",views.loginV,name = "loginV"),
    path("signup", views.signup, name = "signup"),
    path("profile", views.goToProfile, name="myProfile"),
    path("logoutUser", views.logoutUser, name = "logout"),
    path("updateProfile",views.updateProfile,name="updateProfile"),
    path("addMoney",views.updateMoney,name="addMoney"),
    path("myProduts",views.myProducts,name="myProducts"),
    path("notifications",views.notifications,name="notifications"),
    path('deleteUserNotification/<notification_id>', views.deleteUserNotification, name="deleteUserNotification"),
    path('deleteBidNotification/<notification_id>', views.deleteBidNotification, name="deleteBidNotification"),
    path('deleteSystemNotification/<notification_id>', views.deleteSystemNotification, name="deleteSystemNotification"),
    path("deleteUser",views.deleteUser,name="deleteUser"),
    path("myProducts/<int:id_product>/updateStockProduct",views.UpdateStockGeneral.as_view(),name="updateStock"),
    path("myProducts/<int:id_product>/updateBidProduct",views.UpdateBidGeneral.as_view(),name="updateBid"),
    path("myProducts/<int:id_bid>/bidOrder",views.bidOrder,name="bidOrder"),
    path("myProducts/orders",views.orders,name="orders"),
    path("myProducts/<int:id_order>/order",views.order,name="order"),
    path("myShoppings",views.myShoppings,name="myShoppings"),
    path("myShoppings/<int:id_order>/status",views.status,name="status"),
]

users/forms.py
from django import forms
from django.forms import ModelForm, fields
from django.contrib.auth.forms import UserCreationForm
from .models import User
from store.models import BidProduct,StockProduct

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('firstName','lastName','email','city','state',)
        widgets = {
        'password': forms.PasswordInput(),
        }

class LoginForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'E-mail'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña'}))
    fields = ['email', 'password']

class UpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('firstName','lastName','city','state','profilePic',)

class UpdateMoneyForm(forms.ModelForm):
    money = forms.IntegerField(widget=forms.NumberInput(None),min_value=0,initial=0,error_messages={0:"Los créditos deben ser mayor o igual a 1"})
    class Meta:
        model = User
        fields = ['money']

class UpdateStock(forms.ModelForm):
    class Meta:
        model = StockProduct
        fields = ['productName','description','category','price','inventory','isActive']
        
class UpdateBid(forms.ModelForm):
    class Meta:
        model = BidProduct
        fields = ['productName','description','category','isActive']

users/views.py
from django.shortcuts import render
from users.models import BidNotification, User,Bid, UserNotification, SystemNotification
from .forms import UpdateForm, UpdateMoneyForm, UserForm, LoginForm,UpdateBid,UpdateStock
from store.models import BidProduct,StockProduct
from cart.models import Order, OrderItem,OrderBid
from django.shortcuts import render, redirect
from django.views.generic.detail import DetailView
from django.http import HttpResponseNotAllowed
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
def loginV(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(request, email=email,password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                return redirect('core:index')
        else: #User doesn't exist
            return render(request,"users/login.html",{"form":form,"msg":'No existe el usuario'})
            
    return render(request,"users/login.html",{"form":form})
        
def signup(request):
    if request.method == "POST":
        theForm = UserForm(request.POST) #get the form filled out 
        if theForm.is_valid():
            adminEmail = "droseher@gmail.com"
            newUser = theForm.save(commit=False)
            newUser.save()
            newMessage = f"Bienvenido {newUser.firstName}! Gracias por crear una cuenta PulgApp!"
            from_user = User.objects.get(email=adminEmail)
            UserNotification.objects.create(toUser = newUser, message = newMessage, fromUser = from_user)
            login(request,newUser)
            return redirect('core:index')
    else:
        theForm = UserForm()
    return render(request, "users/signup.html", {"form":theForm})
    
def logoutUser(request):
    logout(request)
    return redirect("users:loginV")

@login_required
def goToProfile(request):
    # if request.method == "POST":
    #     return redirect('users:updateProfile')
    curret_user = request.user
    #userName = curret_user.lastName
    return render(request, "users/myProfile.html",{'user':curret_user})

@login_required
def updateProfile(request):
    if request.method == "POST":
        if 'UpdateProfile' in request.POST:
            theForm = UpdateForm(request.POST,request.FILES,instance=request.user)
            theForm.actual_user=request.user 
            if theForm.is_valid():
                theForm.save()
                return redirect('users:myProfile')
        else:
            return redirect('users:myProfile')
    else:
        data={'firstName':request.user.firstName,'lastName':request.user.lastName,
            'city':request.user.city,'state':request.user.state}
        theForm = UpdateForm(None,initial=data)
        return render(request,"users/updateProfile.html",{"form":theForm})
    
@login_required
def deleteUser(request):
    if request.method=="POST":
        if "delete" in request.POST:
            user = User.objects.get(email=request.user.email)
            user.is_active = False
            user.save()
            logout(request)
            return redirect('core:index')
        else:
            return redirect('users:myProfile')        
    return render(request,"users/deleteUser.html")

@login_required
def updateMoney(request):
    if request.method=="POST":
        if "UpdateMoney" in request.POST:
            theForm = UpdateMoneyForm(request.POST,instance=request.user)
            mon1 = request.user.money
            if theForm.is_valid():
                mon = theForm.cleaned_data['money']
                theForm.actual_user = request.user
                theForm.actual_user.money = mon1 + mon
                theForm.save()
                return redirect('users:myProfile')
        else:
            return redirect('users:myProfile')
    theForm = UpdateMoneyForm()
    return render(request,"users/addMoney.html",{"form":theForm})

@login_required
def myProducts(request):
    context={
        'bidProducts':reversed(BidProduct.objects.filter(seller=request.user)),
        'stockProducts':reversed(StockProduct.objects.filter(seller=request.user))
    }
    return render(request,"users/myProducts.html",context)

class UpdateStockGeneral(DetailView):
    form_class = UpdateStock
    template_name = "users/updateMyStockProduct.html"
    
    def get(self,request, *args, **kwargs):
        try:
            product = StockProduct.objects.get(id=kwargs['id_product'],seller=request.user)
            data={'productName':product.productName,'description':product.description,
                'category':product.category,'price':product.price,'inventory':product.inventory
                ,'isActive':product.isActive}
            self.form_class.initial = data
            form = self.form_class(initial=data)
            return render(request,"users/updateMyStockProduct.html",{"form":form})
        except:
            return HttpResponseNotAllowed("Not allowed")
    
    def post(self,request,*args, **kwargs):
        if "UpdateProduct" in request.POST and (not "Delete" in request.POST):
            print("Dentro de UpdateProduct")
            form = UpdateStock(request.POST,request.FILES,instance=StockProduct.objects.get(id=kwargs['id_product']))
            if form.is_valid():
                if(form.cleaned_data['price']<0):
                    messages.warning(self.request,"No puedes ingresar valores negativos")
                else:                
                    form.save()
                    return redirect('users:myProducts')
            return render(request,self.template_name,{'form':form})
        elif "Delete" in request.POST:
            #Parte para eliminar el producto
            print("Dentro de Eliminar")
            product = StockProduct.objects.get(id=kwargs['id_product'])
            product.delete()
            return redirect('users:myProducts')
        elif "Orders" in request.POST:
            return orders(request,kwargs['id_product'])
        else:
            print("Dentro de cancelar")
            return redirect('users:myProducts')
        
def orders(request,id_product):
    orderItem = reversed(OrderItem.objects.filter(product = id_product))
    return render(request,"users/orders.html",{"orderItem":orderItem})

def order(request,id_order):
    orderItem = OrderItem.objects.get(id = id_order)
    if request.user.id != orderItem.product.seller.id:
        return HttpResponseNotAllowed("Not allowed")
    else:
        if request.method=="POST":
            orderItem.shipped = True
            orderItem.save()
            print(orderItem.shipped)
            return redirect('users:myProducts')
        return render(request,"users/order.html",{"orderItem":orderItem})
        
class UpdateBidGeneral(DetailView):
    form_class = UpdateBid
    template_name = "users/updateMyStockProduct.html"
    
    def get(self,request, *args, **kwargs):
        try:
            product = BidProduct.objects.get(id=kwargs['id_product'],seller=request.user)
            if not product.sold:
                data={'productName':product.productName,'description':product.description,
                    'category':product.category,'isActive':product.isActive}
                self.form_class.initial = data
                form = self.form_class(initial=data)
                return render(request,"users/updateMyBidProduct.html",{"form":form,"bid":product})
            else:
                email = product.bidWinner.email
                return render(request,"users/updateMyBidProduct.html",{"bid":product,"email":email})
        except:
            print("No puedes acceder a esta página porque no eres el propietario del producto")
            return HttpResponseNotAllowed("Not allowed")
    
    def post(self,request,*args, **kwargs):
        if "UpdateProduct" in request.POST:
            print("Dentro de UpdateProduct")
            form = UpdateBid(request.POST,request.FILES,instance=BidProduct.objects.get(id=kwargs['id_product']))
            if form.is_valid():
                form.save()
                return redirect('users:myProducts')
            return render(request,self.template_name,{'form':form})
        elif "End" in request.POST:
            #Parte para escoger ganador de bid
            product = BidProduct.objects.get(id = kwargs['id_product'])
            bid = Bid.objects.filter(product = product.id)
            
            for b in bid:
                bidder = b.user
                if b.userBid == product.currentBid:
                    product.bidWinner = b.user
                    product.isActive = False
                    product.sold = True
                    product.save()
                    print("Producto actualizado, ganador seleccionado")
                    print("Ahora el producto no es visible")
                    #Enviar notificacion al ganador
                    newMessage = f'¡Felicidades {b.user.firstName}! ¡Has ganado el bid para el producto: {product.productName}! ¡Vendido a ${product.currentBid}! Comuníquese con {product.seller.email}, por favor.'
                    
                    toSellerMes = f'{b.user.firstName} ha ganado el bid de {product.productName}! ¡Vendido a ${product.currentBid}! Comuníquese con {bidder.email}, por favor.'
                    BidNotification.objects.create(toUser = product.seller, message = toSellerMes,fromBidProduct = product)
                    #BidNotification.objects.create(toUser = bidder, message = newMessage, fromBidProduct = product)    
                else:
                    #Enviar notificaciones a los perdedores
                    newMessage = f'Lo sentimos, {b.user.firstName}. El bid del producto:  {product.productName} ha concluido y NO ganaste.'
                    b.delete()

users/templates/users/addMoney.html
{% extends 'core/layout.html' %} 
{% load static %}   
{% load crispy_forms_tags %} <!--1-->
{% block cssPath %} 
    <link rel="stylesheet" href="{% static 'users/addMoney.css' %}"  type="text/css"/>
{% endblock cssPath %}

{% block title %}Configuracion{% endblock title%}
    
{% block body %}
<div class="infoContainer">
    <p><h1 align="center">Añade créditos a tu cuenta</h1></p>
    <p style="color:#ffbf00" align="center">Tu dinero actual: {{user.money}}</p>
                <div class="img-logo">
                    <span class="logo-circle">
                        <center><img id="logo2" src="{% static 'store/logo.png' %}" alt="PULGAPP">                        
                    </span>
                </div>
    <div align="center" class="form">
        <form method="POST" action="{% url 'users:addMoney' %}" >
            {% csrf_token %}
            {{form.as_p}}
            <button id="buttonLogin" type="submit" name="UpdateMoney">Agregar créditos</button>
            <button id="buttonLogin" type="submit" name="Cancel">Cancelar</button>
        </form>
    </div>
    <script src="{% static 'users/labels2.js'%}"></script>
</div>
{% endblock body %}

users/templates/users/bidOrder.html
{% extends 'core/layout.html' %} 
{% load static %}   

{% block cssPath %} 
<link rel="stylesheet" href="{% static 'store/productTemplate.css' %}"  type="text/css"/>
{% endblock cssPath %}

    {% block title %} Información de orden {% endblock title%}

    {% block body %} 
    <div class="infoContainer">
    <div class="row">
        <div class="col-md-3 register-left my-auto">   
            <div class="pictures">
                <img src="{{product.image.url}}"  alt="Product Image" width="500" height="500" />
            </div>
        </div>
        
        <div class="col-md-9 register-right">
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <div id="littlePadding" class="col">
                            <font style="color:black" align="center">
                        
                            <div class="productDescription">
                                <div class="productName">
                                    <h1>{{ product.productName }}</h1>
                                </div>
                                <div class="description">
                                    <h3>Descripción:</h3>
                                    <p>{{ product.description }}</p>
                                </div>
                                <div class="price">
                                    <h3>A pagar: ${{ product.currentBid }} <h3>
                                </div>
                                <div class="email">
                                    <h3>Contactar con el vendedor a: {{ product.seller.email }} <h3>
                                </div>
                            </font>
                        </div>   
                    </div>
                </div>
            </div>
        </div>
    </div> 
    {% endblock body %}

users/templates/users/deleteUser.html
{% extends 'core/layout.html' %} 
{% load static %}   

{% block cssPath %} 
    <link rel="stylesheet" href="{% static 'store/productUpload.css' %}"  type="text/css"/>
{% endblock cssPath %}

{% block title %}Configuracion{% endblock title%}
    
{% block body %}
<div class="container upload-form">
            <div class="product-title">
                <h1>Eliminar cuenta</h1>
            </div>
    <p><center>¿Estás seguro de hacerlo? :(</p>
    <div class="form">
        <form method="POST" action="{% url 'users:deleteUser' %}" >
            {% csrf_token %}
            {{form.as_p}}
            <button id="bidButton" type="submit" name="delete">Adios!</button>
            <button id="bidButton" type="submit" name="Cancel">Cancelar</button>
        </form>
    </div>
</div>
{% endblock body %}

users/templates/users/login.html
{% extends 'core/layout.html' %}
{% load static %}

{% block cssPath %} 
    <link rel="stylesheet" href="{% static 'users/formStyle.css' %}"  type="text/css"/>
{% endblock cssPath %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
{% block title %}
    LOGIN
{% endblock title %}

{% block body %}
    {{msg}}
    <div class="container">
        <div class="registration-form">
            <form method = "POST" action="{% url 'users:loginV' %}">
                {% csrf_token %}
                <div class="form-icon">
                    <span><i class="icon icon-user"></i></span>
                </div>
                <div class="form-group">
                    {{form.email}}
                </div>
                <div class="form-group">
                    {{form.password}}
                </div>
                <div class="form-group">
                    <button class="btn btn-block" id="btnSubmit" type="submit" value="Login">Iniciar Sesion</button>
                </div>
            </form>
            <div class="social-media">
                <span id="loginQuestion">¿No estas registrado?</span>
                <br>
                <a href="{% url 'users:signup' %}">
                    <button type="button" class="btn btn-block" id="buttonLogin">Registrate aqui</button>
                </a>
                <!-- <button type="button" class="btn btn-block" id="buttonLogin"><a href="{% url 'users:signup' %}">Registrate aqui</a></button> -->
            </div>
        </div>
    </diV>
    <!--<div class="container-login">
        <div class="wrap-login">
        <form method = "POST" action="{% url 'users:loginV' %}" >
            {% csrf_token %}
            <div class="wrap-login2">
                <span class="welcome-title"> Bienvenido </span>
                <br><br><br>
                <div class="UserEmail">
                    {{form.email}}
                </div>
                <div class="UserPassword">
                    {{form.password}}
                </div>
                <div class="wrap-button">
                    <div class="login-button">
                        <button id="btnSubmit" type="submit" value="Login"> Login</button>
                    </div>
                </div>
                <div class="signup-link">
                    <span class="signup-registry">¿No estas registrado?, </span>
                    <a class="signup-text" href="{% url 'users:signup' %}">¡Registrate aqui!</a>
                </div>
            </div>
        </form>
        </div>
    </div>-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
{% endblock body %}

users/templates/users/myProducts.html
{% extends 'core/layout.html' %}

{% block title %}
    INDEX
{% endblock title %}

{% block body %}
    <div class="album py-5 bg-light">
    <div class="container">
    <div class="pb-3 h5">Productos que has subido a nuestra página, da click en ellos para editarlos y para ver las órdenes</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {%for product in stockProducts %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img class="img-fluid" alt="Responsive image" src="{{product.image.url}}">
                        <div class="card-body">
                            <p class="card-text">
                                <a class="text-dark text-decoration-none" href="http://127.0.0.1:8000/myProducts/{{product.id}}/updateStockProduct">{{product.productName}}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{product.sold}} vendidos</small>
                            </div>
                        </div>
                    </div>
                </div>
                {%endfor %}
                {%for product in bidProducts %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img class="img-fluid" alt="Responsive image" src="{{product.image.url}}">
                        <div class="card-body">
                            <p class="card-text">
                                <a class="text-dark text-decoration-none" href="http://127.0.0.1:8000/myProducts/{{product.id}}/updateBidProduct">{{product.productName}}</a>
                            </p>
                            {%if product.sold%}
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">Vendido a {{product.currentBid}}!</small>
                            </div>
                            {%else%}
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">Puja actual: {{product.currentBid}}</small>
                            </div>
                            {%endif%}
                        </div>
                    </div>
                </div>
                {%endfor %}
            </div>
        </div>
    </div>
{% endblock body %}

users/templates/users/myProfile.html
{% extends 'core/layout.html' %} 

{% load static %}   
{% load crispy_forms_tags %} <!--1-->

{% block cssPath %}

<link rel="stylesheet" href="{% static 'users/formStyle.css' %}"  type="text/css"/> 

{% endblock cssPath %}

{% block title %}
My Profile
{% endblock title%}
    
{% block body %}

    {% comment %} <h1>Hola, {{user.firstName|default:'mi estimado'}}!<h1></h1> {% endcomment %}
    <div class="infoContainer">
        <div class="row">
            <div class="col-md-3 register-left my-auto">
              <p>
              <h1>Mi Perfil</h1>
              </p>
                <div class="button">
                <p>
                <a class="modificar" href="{% url 'users:updateProfile' %}">
                <button id="buttonLogin">Modificar perfil</button>
                </a>
                </p>
                <p>
                <a class="modificar" href="{% url 'users:addMoney' %}">
                <button id="buttonLogin">Agregar moneda</button>
                </a>
                </p>
                <a class="modificar" href="{% url 'users:deleteUser'%}">
                <button id="buttonLogin">Eliminar cuenta</button>
                </a>
                </div>
            </div>
            <div class="col-md-9 register-right">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div id="littlePadding" class="col">
                          <font style="color:#f5f5dc" align="center">
                          <h5>
                            <b><p>&emsp;&emsp;&emsp;Nombre: </b>{{user.firstName}}
                            <b>&emsp;&emsp;&emsp;&emsp;&emsp;Apellido:</b> {{user.lastName}}</p>
                            <b><p> &emsp;Correo:</b> {{user.email}}</p>
                            <p><b>Ciudad:</b> {{user.city}}
                            <b>&emsp;&emsp;&emsp;&emsp;&emsp;Estado:</b> {{user.state}}</p>
                             <font style="color:#ffbf00" align="center"><b>Dinero:</b> {{user.money}}</p></font>
                            </h5>
                            &emsp; &emsp;&emsp;&emsp;&emsp; &emsp; &emsp;&emsp;&emsp;&emsp; &emsp; &emsp;&emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;
                            <img class = "profilePic" src="{{request.user.profilePic.url}}"
                            width="260"/>
                           </font>
                        </div>
                    </div>
            </div>
        </div>
    </div>
{% endblock body %}

users/templates/users/notifications.html
{% extends 'core/layout.html' %}

{% block title %}
    notificaciones
{% endblock title %}

{% block body %}
    <div class="album py-5 bg-light">
    <div class="container">
    <div class="pb-3 h5">Notificaciones:</div>
    {% for notification in notifications %}
              <div data-index="{{notification.fromUser}}" class="row mb-4 border product-item">
                <div class="col-md-3 col-lg-2 order-md-first bg-light">
                  <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ notification.fromUser.profilePic.url }}">
                </div>
                <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                  <a href="http://127.0.0.1:8000/products/stock/{{product.id}}" class="text-decoration-none text-reset">
                    <h1 class="h5 pt-2">De: {{ notification.fromUser.firstName }}</h1>
                  </a>
                  <div class="border">
                    <div class="col border-bottom">
                      <div class="row p-3">
                        <div class="col-6">Mensaje: </div>
                            <b>{{ notification.message }}</b>
                      </div>
                    </div>
                    <div class="col">
                      <div class="row p-3">
                        <div class="col-12">
                          <a href = "{% url 'users:deleteUserNotification' notification.id %}" class="btn btn-outline-danger btn-sm">Borrar</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            </div>
            </div>
        {% endfor %}

{% for bidNotification in bidNotifications %}
              <div data-index="{{bidNotification.fromBidProduct}}" class="row mb-4 border product-item">
                <div class="col-md-3 col-lg-2 order-md-first bg-light">
                  <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ bidNotification.fromBidProduct.image.url }}">
                </div>
                <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                  <a href="http://127.0.0.1:8000/products/stock/{{product.id}}" class="text-decoration-none text-reset">
                    <h1 class="h5 pt-2">De la puja: {{ bidNotification.fromBidProduct.productName }}</h1>
                  </a>
                  <div class="border">
                    <div class="col border-bottom">
                      <div class="row p-3">
                        <div class="col-6">Mensaje: </div>
                            <b>{{ bidNotification.message }}</b>
                      </div>
                    </div>
                    <div class="col">
                      <div class="row p-3">
                        <div class="col-12">
                          <a href = "{% url 'users:deleteBidNotification' bidNotification.id %}" class="btn btn-outline-danger btn-sm">Borrar</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}


  {% for systemNotification in systemNotifications %}
              <div data-index="{{ systemNotification.toUser }}" class="row mb-4 border product-item">
                <div class="col-md-3 col-lg-2 order-md-first bg-light">
                  <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ systemNotification.image.url }}">
                </div>
                <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                  <a href="http://127.0.0.1:8000/products/stock/{{product.id}}" class="text-decoration-none text-reset">
                    <h1 class="h5 pt-2">De: PulgApp </h1>
                  </a>
                  <div class="border">
                    <div class="col border-bottom">
                      <div class="row p-3">
                        <div class="col-6">Mensaje: </div>
                            <b>{{ systemNotification.message }}</b>
                      </div>
                    </div>
                    <div class="col">
                      <div class="row p-3">
                        <div class="col-12">
                          <a href = "{% url 'users:deleteSystemNotification' systemNotification.id %}" class="btn btn-outline-danger btn-sm">Borrar</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
            </div>
            </div>
            </div>
        

{% endblock body %}